modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="archiblock_two"
version="0.9.0"
displayName="Archiblock 2"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Fred + Patchouli"
description='''
Expand the palettes and choice of blocks in your builds and aestheti-fy your worlds with Archiblocks' additions, forming a wide array with new wood types, decorative ores, craftable decorations, trinkets, flora and much more.
'''

[[dependencies.archiblock_two]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




