modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="archiblock_two"
version="1.0"
displayName="Archiblock II"
credits="Mod created with Mcreator"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Matia & Fred"
description='''
A Deco Mod
'''

[[dependencies.archiblock_two]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




