
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.archiblocktwo.init;

import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.client.event.ColorHandlerEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import net.mcreator.archiblocktwo.block.ZBlockBlock;
import net.mcreator.archiblocktwo.block.YellowSpoolBlock;
import net.mcreator.archiblocktwo.block.YellowNeonBlockBlock;
import net.mcreator.archiblocktwo.block.YBlockBlock;
import net.mcreator.archiblocktwo.block.XBlockBlock;
import net.mcreator.archiblocktwo.block.WovenWarpedStairsBlock;
import net.mcreator.archiblocktwo.block.WovenWarpedSlabBlock;
import net.mcreator.archiblocktwo.block.WovenWarpedBlockBlock;
import net.mcreator.archiblocktwo.block.WovenWarpedBasketBlock;
import net.mcreator.archiblocktwo.block.WovenSpruceStairsBlock;
import net.mcreator.archiblocktwo.block.WovenSpruceSlabBlock;
import net.mcreator.archiblocktwo.block.WovenSpruceBlockBlock;
import net.mcreator.archiblocktwo.block.WovenSpruceBasketBlock;
import net.mcreator.archiblocktwo.block.WovenMysticMapleStairsBlock;
import net.mcreator.archiblocktwo.block.WovenMysticMapleSlabBlock;
import net.mcreator.archiblocktwo.block.WovenMysticMapleBlockBlock;
import net.mcreator.archiblocktwo.block.WovenMysticMapleBasketBlock;
import net.mcreator.archiblocktwo.block.WovenJungleStairsBlock;
import net.mcreator.archiblocktwo.block.WovenJungleSlabBlock;
import net.mcreator.archiblocktwo.block.WovenJungleBlockBlock;
import net.mcreator.archiblocktwo.block.WovenJungleBasketBlock;
import net.mcreator.archiblocktwo.block.WovenFiberStairsBlock;
import net.mcreator.archiblocktwo.block.WovenFiberSlabBlock;
import net.mcreator.archiblocktwo.block.WovenFiberBlockBlock;
import net.mcreator.archiblocktwo.block.WovenDarkOakStairsBlock;
import net.mcreator.archiblocktwo.block.WovenDarkOakSlabBlock;
import net.mcreator.archiblocktwo.block.WovenDarkOakBlockBlock;
import net.mcreator.archiblocktwo.block.WovenDarkOakBasketBlock;
import net.mcreator.archiblocktwo.block.WovenCrimsonStairsBlock;
import net.mcreator.archiblocktwo.block.WovenCrimsonSlabBlock;
import net.mcreator.archiblocktwo.block.WovenCrimsonBlockBlock;
import net.mcreator.archiblocktwo.block.WovenCrimsonBasketBlock;
import net.mcreator.archiblocktwo.block.WovenBirchStairsBlock;
import net.mcreator.archiblocktwo.block.WovenBirchSlabBlock;
import net.mcreator.archiblocktwo.block.WovenBirchBlockBlock;
import net.mcreator.archiblocktwo.block.WovenBirchBasketBlock;
import net.mcreator.archiblocktwo.block.WovenBasketSandBlock;
import net.mcreator.archiblocktwo.block.WovenBasketPodzolBlock;
import net.mcreator.archiblocktwo.block.WovenBasketMyceliumBlock;
import net.mcreator.archiblocktwo.block.WovenBasketGrassBlock;
import net.mcreator.archiblocktwo.block.WovenBasketDirtBlock;
import net.mcreator.archiblocktwo.block.WovenBasketBlock;
import net.mcreator.archiblocktwo.block.WovenAcaciaStairsBlock;
import net.mcreator.archiblocktwo.block.WovenAcaciaSlabBlock;
import net.mcreator.archiblocktwo.block.WovenAcaciaBlockBlock;
import net.mcreator.archiblocktwo.block.WovenAcaciaBasketBlock;
import net.mcreator.archiblocktwo.block.WhiteSpoolBlock;
import net.mcreator.archiblocktwo.block.WhiteNeonBlockBlock;
import net.mcreator.archiblocktwo.block.WeepingVineCoveredNetherBricksBlock;
import net.mcreator.archiblocktwo.block.WeepingVineCoveredNetherBrickTilesBlock;
import net.mcreator.archiblocktwo.block.WeepingVineCoveredNetherBrickPlateBlock;
import net.mcreator.archiblocktwo.block.WeepingVineCoveredNetherBrickPillarBlock;
import net.mcreator.archiblocktwo.block.WeepingVineCoveredChiselledNetherBricksBlock;
import net.mcreator.archiblocktwo.block.WeepingVineCoveredBigNetherBricksBlock;
import net.mcreator.archiblocktwo.block.WarpedBasketSandBlock;
import net.mcreator.archiblocktwo.block.WarpedBasketPodzolBlock;
import net.mcreator.archiblocktwo.block.WarpedBasketMyceliumBlock;
import net.mcreator.archiblocktwo.block.WarpedBasketMossBlock;
import net.mcreator.archiblocktwo.block.WarpedBasketDirtBlock;
import net.mcreator.archiblocktwo.block.WBlockBlock;
import net.mcreator.archiblocktwo.block.VBlockBlock;
import net.mcreator.archiblocktwo.block.UBlockBlock;
import net.mcreator.archiblocktwo.block.TwistingVineCoveredNetherBricksBlock;
import net.mcreator.archiblocktwo.block.TwistingVineCoveredNetherBrickTilesBlock;
import net.mcreator.archiblocktwo.block.TwistingVineCoveredNetherBrickPlateBlock;
import net.mcreator.archiblocktwo.block.TwistingVineCoveredNetherBrickPillarBlock;
import net.mcreator.archiblocktwo.block.TwistingVineCoveredChiselledNetherBricksBlock;
import net.mcreator.archiblocktwo.block.TwistingVineCoveredBigNetherBricksBlock;
import net.mcreator.archiblocktwo.block.TwilightwaveTilesBlock;
import net.mcreator.archiblocktwo.block.TwilightwavePillarTopBlock;
import net.mcreator.archiblocktwo.block.TwilightwavePillarBlock;
import net.mcreator.archiblocktwo.block.TwilightwaveBricksBlock;
import net.mcreator.archiblocktwo.block.TwilightwaveBrickWallBlock;
import net.mcreator.archiblocktwo.block.TwilightwaveBrickStairsBlock;
import net.mcreator.archiblocktwo.block.TwilightwaveBrickSlabBlock;
import net.mcreator.archiblocktwo.block.TwilightwaveBlockBlock;
import net.mcreator.archiblocktwo.block.TwilightTilesBlock;
import net.mcreator.archiblocktwo.block.TwilightPillarTopBlock;
import net.mcreator.archiblocktwo.block.TwilightPillarBlock;
import net.mcreator.archiblocktwo.block.TwilightOreBlock;
import net.mcreator.archiblocktwo.block.TwilightBricksBlock;
import net.mcreator.archiblocktwo.block.TwilightBrickWallBlock;
import net.mcreator.archiblocktwo.block.TwilightBrickStairsBlock;
import net.mcreator.archiblocktwo.block.TwilightBrickSlabBlock;
import net.mcreator.archiblocktwo.block.TwilightBlockBlock;
import net.mcreator.archiblocktwo.block.TriangleBlockBlock;
import net.mcreator.archiblocktwo.block.TopazTilesBlock;
import net.mcreator.archiblocktwo.block.TopazStoneOreBlock;
import net.mcreator.archiblocktwo.block.TopazPillarsBlock;
import net.mcreator.archiblocktwo.block.TopazGraniteOreBlock;
import net.mcreator.archiblocktwo.block.TopazBricksBlock;
import net.mcreator.archiblocktwo.block.TopazBlockBlock;
import net.mcreator.archiblocktwo.block.TiledArchiumBlock;
import net.mcreator.archiblocktwo.block.TiedbambooBlockBlock;
import net.mcreator.archiblocktwo.block.TBlockBlock;
import net.mcreator.archiblocktwo.block.SugiliteTilesBlock;
import net.mcreator.archiblocktwo.block.SugilitePillarBlock;
import net.mcreator.archiblocktwo.block.SugiliteOreBlock;
import net.mcreator.archiblocktwo.block.SugiliteBricksBlock;
import net.mcreator.archiblocktwo.block.SugiliteBlockBlock;
import net.mcreator.archiblocktwo.block.StrippedMysticMapleWoodBlock;
import net.mcreator.archiblocktwo.block.StrippedMysticMapleLogBlock;
import net.mcreator.archiblocktwo.block.StringMeshBlock;
import net.mcreator.archiblocktwo.block.StoneTilesBlock;
import net.mcreator.archiblocktwo.block.StonePillarBlock;
import net.mcreator.archiblocktwo.block.StarBlockBlock;
import net.mcreator.archiblocktwo.block.SquareBlockBlock;
import net.mcreator.archiblocktwo.block.SpruceBasketSandBlock;
import net.mcreator.archiblocktwo.block.SpruceBasketPodzolBlock;
import net.mcreator.archiblocktwo.block.SpruceBasketMyceliumBlock;
import net.mcreator.archiblocktwo.block.SpruceBasketMossBlock;
import net.mcreator.archiblocktwo.block.SpruceBasketDirtBlock;
import net.mcreator.archiblocktwo.block.SnowyStoneTilesBlock;
import net.mcreator.archiblocktwo.block.SnowyStoneStairsBlock;
import net.mcreator.archiblocktwo.block.SnowyStoneSlabBlock;
import net.mcreator.archiblocktwo.block.SnowyStonePillarBlock;
import net.mcreator.archiblocktwo.block.SnowyStoneBricksBlock;
import net.mcreator.archiblocktwo.block.SnowyStoneBrickStairsBlock;
import net.mcreator.archiblocktwo.block.SnowyStoneBrickSlabBlock;
import net.mcreator.archiblocktwo.block.SnowyStoneBlock;
import net.mcreator.archiblocktwo.block.SnowySmallStoneBricksBlock;
import net.mcreator.archiblocktwo.block.SnowyCutStoneStairsBlock;
import net.mcreator.archiblocktwo.block.SnowyCutStoneSlabBlock;
import net.mcreator.archiblocktwo.block.SnowyCutStoneBlock;
import net.mcreator.archiblocktwo.block.SnowyCobblestoneStairsBlock;
import net.mcreator.archiblocktwo.block.SnowyCobblestoneSlabBlock;
import net.mcreator.archiblocktwo.block.SnowyCobblestoneBlock;
import net.mcreator.archiblocktwo.block.SnowyChiselledStoneBricksBlock;
import net.mcreator.archiblocktwo.block.SnowPillarBlock;
import net.mcreator.archiblocktwo.block.SnowBricksBlock;
import net.mcreator.archiblocktwo.block.SmoothSmokyQuartzWallBlock;
import net.mcreator.archiblocktwo.block.SmoothSmokyQuartzStairsBlock;
import net.mcreator.archiblocktwo.block.SmoothSmokyQuartzSlabBlock;
import net.mcreator.archiblocktwo.block.SmoothSmokyQuartzBlock;
import net.mcreator.archiblocktwo.block.SmoothRoseQuartzWallBlock;
import net.mcreator.archiblocktwo.block.SmoothRoseQuartzStairsBlock;
import net.mcreator.archiblocktwo.block.SmoothRoseQuartzSlabBlock;
import net.mcreator.archiblocktwo.block.SmoothRoseQuartzBlock;
import net.mcreator.archiblocktwo.block.SmokyWall2Block;
import net.mcreator.archiblocktwo.block.SmokyStairs2Block;
import net.mcreator.archiblocktwo.block.SmokySlab2Block;
import net.mcreator.archiblocktwo.block.SmokyQuartzWallBlock;
import net.mcreator.archiblocktwo.block.SmokyQuartzStairsBlock;
import net.mcreator.archiblocktwo.block.SmokyQuartzSlabBlock;
import net.mcreator.archiblocktwo.block.SmokyQuartzPillarBlock;
import net.mcreator.archiblocktwo.block.SmokyQuartzOreBlock;
import net.mcreator.archiblocktwo.block.SmokyQuartzBricksBlock;
import net.mcreator.archiblocktwo.block.SmokyQuartzBricks2Block;
import net.mcreator.archiblocktwo.block.SmokyQuartzBlockBlock;
import net.mcreator.archiblocktwo.block.SmokyBrickWallBlock;
import net.mcreator.archiblocktwo.block.SmokyBrickStairsBlock;
import net.mcreator.archiblocktwo.block.SmokyBrickSlabBlock;
import net.mcreator.archiblocktwo.block.SmallStoneBricksBlock;
import net.mcreator.archiblocktwo.block.SmallSnowBricksBlock;
import net.mcreator.archiblocktwo.block.SmallObsidianBricksBlock;
import net.mcreator.archiblocktwo.block.SmallClayBrickTilesBlock;
import net.mcreator.archiblocktwo.block.SlantedShinglesSideBlock;
import net.mcreator.archiblocktwo.block.SlantedClayShinglesBlock;
import net.mcreator.archiblocktwo.block.SideSnowyStonePillarBlock;
import net.mcreator.archiblocktwo.block.ScarletRoseShrubBlock;
import net.mcreator.archiblocktwo.block.ScarletRoseBushBlock;
import net.mcreator.archiblocktwo.block.ScarletRoseBlock;
import net.mcreator.archiblocktwo.block.SapphireTilesBlock;
import net.mcreator.archiblocktwo.block.SapphirePillarBlock;
import net.mcreator.archiblocktwo.block.SapphireOreBlock;
import net.mcreator.archiblocktwo.block.SapphireDioriteOreBlock;
import net.mcreator.archiblocktwo.block.SapphireBricksBlock;
import net.mcreator.archiblocktwo.block.SapphireBlockBlock;
import net.mcreator.archiblocktwo.block.SandstoneTilesBlock;
import net.mcreator.archiblocktwo.block.SandstoneTileStairsBlock;
import net.mcreator.archiblocktwo.block.SandstoneTileSlabBlock;
import net.mcreator.archiblocktwo.block.SandstonePillarBlock;
import net.mcreator.archiblocktwo.block.SandstoneBricksBlock;
import net.mcreator.archiblocktwo.block.SandstoneBrickWallBlock;
import net.mcreator.archiblocktwo.block.SandstoneBrickStairsBlock;
import net.mcreator.archiblocktwo.block.SandstoneBrickSlabBlock;
import net.mcreator.archiblocktwo.block.SBlockBlock;
import net.mcreator.archiblocktwo.block.RubyTilesBlock;
import net.mcreator.archiblocktwo.block.RubyPillarBlock;
import net.mcreator.archiblocktwo.block.RubyOreBlock;
import net.mcreator.archiblocktwo.block.RubyBricksBlock;
import net.mcreator.archiblocktwo.block.RubyBlockBlock;
import net.mcreator.archiblocktwo.block.RoseShrubBlock;
import net.mcreator.archiblocktwo.block.RoseQuartzWallBlock;
import net.mcreator.archiblocktwo.block.RoseQuartzStairsBlock;
import net.mcreator.archiblocktwo.block.RoseQuartzSlabBlock;
import net.mcreator.archiblocktwo.block.RoseQuartzPillarBlock;
import net.mcreator.archiblocktwo.block.RoseQuartzOreBlock;
import net.mcreator.archiblocktwo.block.RoseQuartzBricksBlock;
import net.mcreator.archiblocktwo.block.RoseQuartzBricks2Block;
import net.mcreator.archiblocktwo.block.RoseQuartzBrickStairsBlock;
import net.mcreator.archiblocktwo.block.RoseQuartzBlockBlock;
import net.mcreator.archiblocktwo.block.RoseBrickWallBlock;
import net.mcreator.archiblocktwo.block.RoseBrickWall2Block;
import net.mcreator.archiblocktwo.block.RoseBrickStairs2Block;
import net.mcreator.archiblocktwo.block.RoseBrickSlabBlock;
import net.mcreator.archiblocktwo.block.RoseBrickSlab2Block;
import net.mcreator.archiblocktwo.block.RoseBlock;
import net.mcreator.archiblocktwo.block.RedSpoolBlock;
import net.mcreator.archiblocktwo.block.RedSlantedShinglesSideBlock;
import net.mcreator.archiblocktwo.block.RedSlantedClayShinglesBlock;
import net.mcreator.archiblocktwo.block.RedNeonBlockBlock;
import net.mcreator.archiblocktwo.block.RedClayShinglesSlabBlock;
import net.mcreator.archiblocktwo.block.RedClayShinglesBlock;
import net.mcreator.archiblocktwo.block.RedClayBrickTilesBlock;
import net.mcreator.archiblocktwo.block.RedClayBrickSmallTilesBlock;
import net.mcreator.archiblocktwo.block.RedClayBrickPavementBlock;
import net.mcreator.archiblocktwo.block.RedClayBrickBlockBlock;
import net.mcreator.archiblocktwo.block.RedBigClayBricksBlock;
import net.mcreator.archiblocktwo.block.RawTwilightwaveBlockBlock;
import net.mcreator.archiblocktwo.block.RawTwilightBlockBlock;
import net.mcreator.archiblocktwo.block.RawLushTwilightBlockBlock;
import net.mcreator.archiblocktwo.block.RBlockBlock;
import net.mcreator.archiblocktwo.block.QuestionMarkBlockBlock;
import net.mcreator.archiblocktwo.block.QBlockBlock;
import net.mcreator.archiblocktwo.block.PurpleSpoolBlock;
import net.mcreator.archiblocktwo.block.PurpleNeonBlockBlock;
import net.mcreator.archiblocktwo.block.PolishedMarbleStairsBlock;
import net.mcreator.archiblocktwo.block.PolishedMarbleSlabBlock;
import net.mcreator.archiblocktwo.block.PolishedMarbleBricksBlock;
import net.mcreator.archiblocktwo.block.PolishedMarbleBrickWallBlock;
import net.mcreator.archiblocktwo.block.PolishedMarbleBrickStairsBlock;
import net.mcreator.archiblocktwo.block.PolishedMarbleBrickSlabBlock;
import net.mcreator.archiblocktwo.block.PolishedMarbleBlock;
import net.mcreator.archiblocktwo.block.PitchdarkBlockBlock;
import net.mcreator.archiblocktwo.block.PinkSpoolBlock;
import net.mcreator.archiblocktwo.block.PinkRoseShrubBlock;
import net.mcreator.archiblocktwo.block.PinkRoseBushBlock;
import net.mcreator.archiblocktwo.block.PinkRoseBlock;
import net.mcreator.archiblocktwo.block.PinkNeonBlockBlock;
import net.mcreator.archiblocktwo.block.PeriodBlockBlock;
import net.mcreator.archiblocktwo.block.PackedIceTilesBlock;
import net.mcreator.archiblocktwo.block.PackedIcePillarBlock;
import net.mcreator.archiblocktwo.block.PackedIceBricksBlock;
import net.mcreator.archiblocktwo.block.PBlockBlock;
import net.mcreator.archiblocktwo.block.OrangeSpoolBlock;
import net.mcreator.archiblocktwo.block.OrangeNeonBlockBlock;
import net.mcreator.archiblocktwo.block.OliveRoseShrubBlock;
import net.mcreator.archiblocktwo.block.OliveRoseBushBlock;
import net.mcreator.archiblocktwo.block.OliveRoseBlock;
import net.mcreator.archiblocktwo.block.ObsidianTilesBlock;
import net.mcreator.archiblocktwo.block.ObsidianPillarBlock;
import net.mcreator.archiblocktwo.block.ObsidianBricksBlock;
import net.mcreator.archiblocktwo.block.ObsidianBrickWallBlock;
import net.mcreator.archiblocktwo.block.ObsidianBrickStairsBlock;
import net.mcreator.archiblocktwo.block.ObsidianBrickSlabBlock;
import net.mcreator.archiblocktwo.block.OBlockBlock;
import net.mcreator.archiblocktwo.block.NetherBrickTilesBlock;
import net.mcreator.archiblocktwo.block.NetherBrickTileWallBlock;
import net.mcreator.archiblocktwo.block.NetherBrickTileStairsBlock;
import net.mcreator.archiblocktwo.block.NetherBrickTileSlabBlock;
import net.mcreator.archiblocktwo.block.NetherBrickPlateWallBlock;
import net.mcreator.archiblocktwo.block.NetherBrickPlateStairsBlock;
import net.mcreator.archiblocktwo.block.NetherBrickPlateSlabBlock;
import net.mcreator.archiblocktwo.block.NetherBrickPlateBlock;
import net.mcreator.archiblocktwo.block.NetherBrickPillarBlock;
import net.mcreator.archiblocktwo.block.NBlockBlock;
import net.mcreator.archiblocktwo.block.MysticMapleWoodBlock;
import net.mcreator.archiblocktwo.block.MysticMapleTrapdoorBlock;
import net.mcreator.archiblocktwo.block.MysticMapleStairsBlock;
import net.mcreator.archiblocktwo.block.MysticMapleSlabBlock;
import net.mcreator.archiblocktwo.block.MysticMapleSaplingBlock;
import net.mcreator.archiblocktwo.block.MysticMaplePressurePlateBlock;
import net.mcreator.archiblocktwo.block.MysticMaplePlanksBlock;
import net.mcreator.archiblocktwo.block.MysticMapleLogBlock;
import net.mcreator.archiblocktwo.block.MysticMapleLeavesBlock;
import net.mcreator.archiblocktwo.block.MysticMapleFenceGateBlock;
import net.mcreator.archiblocktwo.block.MysticMapleFenceBlock;
import net.mcreator.archiblocktwo.block.MysticMapleDoorBlock;
import net.mcreator.archiblocktwo.block.MysticMapleButtonBlock;
import net.mcreator.archiblocktwo.block.MysticBasketSandBlock;
import net.mcreator.archiblocktwo.block.MysticBasketPodzolBlock;
import net.mcreator.archiblocktwo.block.MysticBasketMyceliumBlock;
import net.mcreator.archiblocktwo.block.MysticBasketMossBlock;
import net.mcreator.archiblocktwo.block.MysticBasketDirtBlock;
import net.mcreator.archiblocktwo.block.MossyStoneTilesBlock;
import net.mcreator.archiblocktwo.block.MossyStonePillarBlock;
import net.mcreator.archiblocktwo.block.MossySmallStoneBricksBlock;
import net.mcreator.archiblocktwo.block.MossyCrackedStoneBlock;
import net.mcreator.archiblocktwo.block.MarbleWallBlock;
import net.mcreator.archiblocktwo.block.MarbleTilesBlock;
import net.mcreator.archiblocktwo.block.MarbleTileWallBlock;
import net.mcreator.archiblocktwo.block.MarbleTileStairsBlock;
import net.mcreator.archiblocktwo.block.MarbleTileSlabBlock;
import net.mcreator.archiblocktwo.block.MarbleStairsBlock;
import net.mcreator.archiblocktwo.block.MarbleSmallBricksBlock;
import net.mcreator.archiblocktwo.block.MarbleSlabBlock;
import net.mcreator.archiblocktwo.block.MarblePillarBlock;
import net.mcreator.archiblocktwo.block.MarbleBricksBlock;
import net.mcreator.archiblocktwo.block.MarbleBrickWallBlock;
import net.mcreator.archiblocktwo.block.MarbleBrickStairsBlock;
import net.mcreator.archiblocktwo.block.MarbleBrickSlabBlock;
import net.mcreator.archiblocktwo.block.MarbleBlock;
import net.mcreator.archiblocktwo.block.MagentaSpoolBlock;
import net.mcreator.archiblocktwo.block.MagentaNeonBlockBlock;
import net.mcreator.archiblocktwo.block.MBlockBlock;
import net.mcreator.archiblocktwo.block.LushTwilightTilesBlock;
import net.mcreator.archiblocktwo.block.LushTwilightPillarTopBlock;
import net.mcreator.archiblocktwo.block.LushTwilightPillarBlock;
import net.mcreator.archiblocktwo.block.LushTwilightBricksBlock;
import net.mcreator.archiblocktwo.block.LushTwilightBrickWallBlock;
import net.mcreator.archiblocktwo.block.LushTwilightBrickStairsBlock;
import net.mcreator.archiblocktwo.block.LushTwilightBrickSlabBlock;
import net.mcreator.archiblocktwo.block.LushTwilightBlockBlock;
import net.mcreator.archiblocktwo.block.LineBlockBlock;
import net.mcreator.archiblocktwo.block.LimeSpoolBlock;
import net.mcreator.archiblocktwo.block.LimeNeonBlockBlock;
import net.mcreator.archiblocktwo.block.LightGraySpoolBlock;
import net.mcreator.archiblocktwo.block.LightGrayNeonBlockBlock;
import net.mcreator.archiblocktwo.block.LightBlueSpoolBlock;
import net.mcreator.archiblocktwo.block.LightBlueNeonBlockBlock;
import net.mcreator.archiblocktwo.block.LCzBlockBlock;
import net.mcreator.archiblocktwo.block.LCyBlockBlock;
import net.mcreator.archiblocktwo.block.LCxBlockBlock;
import net.mcreator.archiblocktwo.block.LCwBlockBlock;
import net.mcreator.archiblocktwo.block.LCvBlockBlock;
import net.mcreator.archiblocktwo.block.LCuBlockBlock;
import net.mcreator.archiblocktwo.block.LCtBlockBlock;
import net.mcreator.archiblocktwo.block.LCsBlockBlock;
import net.mcreator.archiblocktwo.block.LCrBlockBlock;
import net.mcreator.archiblocktwo.block.LCqBlockBlock;
import net.mcreator.archiblocktwo.block.LCpBlockBlock;
import net.mcreator.archiblocktwo.block.LCoBlockBlock;
import net.mcreator.archiblocktwo.block.LCnBlockBlock;
import net.mcreator.archiblocktwo.block.LCmBlockBlock;
import net.mcreator.archiblocktwo.block.LClBlockBlock;
import net.mcreator.archiblocktwo.block.LCkBlockBlock;
import net.mcreator.archiblocktwo.block.LCjBlockBlock;
import net.mcreator.archiblocktwo.block.LCiBlockBlock;
import net.mcreator.archiblocktwo.block.LChBlockBlock;
import net.mcreator.archiblocktwo.block.LCgBlockBlock;
import net.mcreator.archiblocktwo.block.LCfBlockBlock;
import net.mcreator.archiblocktwo.block.LCeBlockBlock;
import net.mcreator.archiblocktwo.block.LCdBlockBlock;
import net.mcreator.archiblocktwo.block.LCcBlockBlock;
import net.mcreator.archiblocktwo.block.LCbBlockBlock;
import net.mcreator.archiblocktwo.block.LCaBlockBlock;
import net.mcreator.archiblocktwo.block.LBlockBlock;
import net.mcreator.archiblocktwo.block.KBlockBlock;
import net.mcreator.archiblocktwo.block.JungleBasketSandBlock;
import net.mcreator.archiblocktwo.block.JungleBasketPodzolBlock;
import net.mcreator.archiblocktwo.block.JungleBasketMyceliumBlock;
import net.mcreator.archiblocktwo.block.JungleBasketMossBlock;
import net.mcreator.archiblocktwo.block.JungleBasketDirtBlock;
import net.mcreator.archiblocktwo.block.JBlockBlock;
import net.mcreator.archiblocktwo.block.IceTilesBlock;
import net.mcreator.archiblocktwo.block.IcePillarBlock;
import net.mcreator.archiblocktwo.block.IceBricksBlock;
import net.mcreator.archiblocktwo.block.IBlockBlock;
import net.mcreator.archiblocktwo.block.HalfDentedBrassTilesBlock;
import net.mcreator.archiblocktwo.block.HalfDentedBrassTIleSlabBlock;
import net.mcreator.archiblocktwo.block.HalfDentedBrassBlockStairsBlock;
import net.mcreator.archiblocktwo.block.HBlockBlock;
import net.mcreator.archiblocktwo.block.GreenSpoolBlock;
import net.mcreator.archiblocktwo.block.GreenNeonBlockBlock;
import net.mcreator.archiblocktwo.block.GraySpoolBlock;
import net.mcreator.archiblocktwo.block.GrayNeonBlockBlock;
import net.mcreator.archiblocktwo.block.GraniteTilesBlock;
import net.mcreator.archiblocktwo.block.GraniteSmallBricksBlock;
import net.mcreator.archiblocktwo.block.GranitePillarBlock;
import net.mcreator.archiblocktwo.block.GraniteCutPillarBlock;
import net.mcreator.archiblocktwo.block.GraniteBricksBlock;
import net.mcreator.archiblocktwo.block.GraniteBrickWallBlock;
import net.mcreator.archiblocktwo.block.GraniteBrickStairsBlock;
import net.mcreator.archiblocktwo.block.GraniteBrickSlabBlock;
import net.mcreator.archiblocktwo.block.GlowingEyesRoundStareBlock;
import net.mcreator.archiblocktwo.block.GlowingEyesRoundBlinkBlock;
import net.mcreator.archiblocktwo.block.GlowingEyesDotsBlock;
import net.mcreator.archiblocktwo.block.GBlockBlock;
import net.mcreator.archiblocktwo.block.FretPatternedMarbleBlock;
import net.mcreator.archiblocktwo.block.FramedStringMeshBlock;
import net.mcreator.archiblocktwo.block.FancyDioritePillarBlock;
import net.mcreator.archiblocktwo.block.FBlockBlock;
import net.mcreator.archiblocktwo.block.ExclamationMarkBlockBlock;
import net.mcreator.archiblocktwo.block.EmptiedArchiumBlock;
import net.mcreator.archiblocktwo.block.EBlockBlock;
import net.mcreator.archiblocktwo.block.DriedTiedBambooBlockBlock;
import net.mcreator.archiblocktwo.block.DriedCarvedBambooPlanksBlock;
import net.mcreator.archiblocktwo.block.DriedBambooWindChimesBlock;
import net.mcreator.archiblocktwo.block.DriedBambooPlanksBlock;
import net.mcreator.archiblocktwo.block.DriedBambooPlankStairsBlock;
import net.mcreator.archiblocktwo.block.DriedBambooPlankSlabBlock;
import net.mcreator.archiblocktwo.block.DriedBambooPlankFenceGateBlock;
import net.mcreator.archiblocktwo.block.DriedBambooPlankFenceBlock;
import net.mcreator.archiblocktwo.block.DriedBambooLadderBlock;
import net.mcreator.archiblocktwo.block.DriedBambooDreamcatcherBlock;
import net.mcreator.archiblocktwo.block.DriedBambooBlock;
import net.mcreator.archiblocktwo.block.DriedBambooBasketBlock;
import net.mcreator.archiblocktwo.block.DotBlockBlock;
import net.mcreator.archiblocktwo.block.DioriteTilesBlock;
import net.mcreator.archiblocktwo.block.DioriteTileWallBlock;
import net.mcreator.archiblocktwo.block.DioriteTileStairsBlock;
import net.mcreator.archiblocktwo.block.DioriteTileSlabBlock;
import net.mcreator.archiblocktwo.block.DioritePillarBlock;
import net.mcreator.archiblocktwo.block.DioriteBricksBlock;
import net.mcreator.archiblocktwo.block.DioriteBrickWallBlock;
import net.mcreator.archiblocktwo.block.DioriteBrickStairsBlock;
import net.mcreator.archiblocktwo.block.DioriteBrickSlabBlock;
import net.mcreator.archiblocktwo.block.DiamondSymbolBlockBlock;
import net.mcreator.archiblocktwo.block.DentedBrassTilesBlock;
import net.mcreator.archiblocktwo.block.DentedBrassTileSlabBlock;
import net.mcreator.archiblocktwo.block.DentedBrassBlockStairsBlock;
import net.mcreator.archiblocktwo.block.DarkOakBasketSandBlock;
import net.mcreator.archiblocktwo.block.DarkOakBasketPodzolBlock;
import net.mcreator.archiblocktwo.block.DarkOakBasketMyceliumBlock;
import net.mcreator.archiblocktwo.block.DarkOakBasketMossBlock;
import net.mcreator.archiblocktwo.block.DarkOakBasketDirtBlock;
import net.mcreator.archiblocktwo.block.DBlockBlock;
import net.mcreator.archiblocktwo.block.CyanSpoolBlock;
import net.mcreator.archiblocktwo.block.CyanNeonBlockBlock;
import net.mcreator.archiblocktwo.block.CutStoneWallBlock;
import net.mcreator.archiblocktwo.block.CutStoneStairsBlock;
import net.mcreator.archiblocktwo.block.CutStoneSlabBlock;
import net.mcreator.archiblocktwo.block.CutStoneBlock;
import net.mcreator.archiblocktwo.block.CutSnowBlock;
import net.mcreator.archiblocktwo.block.CutPackedIceBlock;
import net.mcreator.archiblocktwo.block.CutObsidianBlock;
import net.mcreator.archiblocktwo.block.CutMarbleBlock;
import net.mcreator.archiblocktwo.block.CutIceBlock;
import net.mcreator.archiblocktwo.block.CutGraniteWallBlock;
import net.mcreator.archiblocktwo.block.CutGraniteStairsBlock;
import net.mcreator.archiblocktwo.block.CutGraniteSlabBlock;
import net.mcreator.archiblocktwo.block.CutGraniteBlock;
import net.mcreator.archiblocktwo.block.CutDioriteBlock;
import net.mcreator.archiblocktwo.block.CutBrassSlabBlock;
import net.mcreator.archiblocktwo.block.CrimsonBasketSandBlock;
import net.mcreator.archiblocktwo.block.CrimsonBasketPodzolBlock;
import net.mcreator.archiblocktwo.block.CrimsonBasketMyceliumBlock;
import net.mcreator.archiblocktwo.block.CrimsonBasketMossBlock;
import net.mcreator.archiblocktwo.block.CrimsonBasketDirtBlock;
import net.mcreator.archiblocktwo.block.CrackedStoneTilesBlock;
import net.mcreator.archiblocktwo.block.CrackedStonePillarBlock;
import net.mcreator.archiblocktwo.block.CrackedNetherBrickTilesBlock;
import net.mcreator.archiblocktwo.block.CrackedNetherBrickPlateBlock;
import net.mcreator.archiblocktwo.block.CrackedCutStoneBlock;
import net.mcreator.archiblocktwo.block.CrackedBigNetherBricksBlock;
import net.mcreator.archiblocktwo.block.ClayShinglesSlabBlock;
import net.mcreator.archiblocktwo.block.ClayShinglesBlock;
import net.mcreator.archiblocktwo.block.ClayBrickTilesBlock;
import net.mcreator.archiblocktwo.block.ClayBrickPavementBlock;
import net.mcreator.archiblocktwo.block.ClayBrickBlockBlock;
import net.mcreator.archiblocktwo.block.CircleBlockBlock;
import net.mcreator.archiblocktwo.block.ChiselledTwilightwaveBricksBlock;
import net.mcreator.archiblocktwo.block.ChiselledTwilightBricksBlock;
import net.mcreator.archiblocktwo.block.ChiselledSmokyQuartzBlock;
import net.mcreator.archiblocktwo.block.ChiselledSandstoneTilesBlock;
import net.mcreator.archiblocktwo.block.ChiselledSandstoneTileStairsBlock;
import net.mcreator.archiblocktwo.block.ChiselledSandstoneTileSlabBlock;
import net.mcreator.archiblocktwo.block.ChiselledSandstonePillarBlock;
import net.mcreator.archiblocktwo.block.ChiselledSandstoneBricksBlock;
import net.mcreator.archiblocktwo.block.ChiselledSandstoneBrickWallBlock;
import net.mcreator.archiblocktwo.block.ChiselledSandstoneBrickStairsBlock;
import net.mcreator.archiblocktwo.block.ChiselledSandstoneBrickSlabBlock;
import net.mcreator.archiblocktwo.block.ChiselledRoseQuartzBlock;
import net.mcreator.archiblocktwo.block.ChiselledPackedIceBlock;
import net.mcreator.archiblocktwo.block.ChiselledObsidianWallBlock;
import net.mcreator.archiblocktwo.block.ChiselledObsidianStairsBlock;
import net.mcreator.archiblocktwo.block.ChiselledObsidianSlabBlock;
import net.mcreator.archiblocktwo.block.ChiselledObsidianBlock;
import net.mcreator.archiblocktwo.block.ChiselledMarbleBlock;
import net.mcreator.archiblocktwo.block.ChiselledLushTwilightBricksBlock;
import net.mcreator.archiblocktwo.block.ChiselledIceBlock;
import net.mcreator.archiblocktwo.block.ChiselledGraniteBlock;
import net.mcreator.archiblocktwo.block.ChiselledDioriteBlock;
import net.mcreator.archiblocktwo.block.ChiselledAndesiteBlock;
import net.mcreator.archiblocktwo.block.CarvedBambooPlanksBlock;
import net.mcreator.archiblocktwo.block.CBlockBlock;
import net.mcreator.archiblocktwo.block.ButtermilkRoseShrubBlock;
import net.mcreator.archiblocktwo.block.ButtermilkRoseBushBlock;
import net.mcreator.archiblocktwo.block.ButtermilkRoseBlock;
import net.mcreator.archiblocktwo.block.BrownSpoolBlock;
import net.mcreator.archiblocktwo.block.BrownNeonBlockBlock;
import net.mcreator.archiblocktwo.block.BrassTrapdoorBlock;
import net.mcreator.archiblocktwo.block.BrassTilesStairsBlock;
import net.mcreator.archiblocktwo.block.BrassTilesRBlock;
import net.mcreator.archiblocktwo.block.BrassTileSlabBlock;
import net.mcreator.archiblocktwo.block.BrassPipeBlock;
import net.mcreator.archiblocktwo.block.BrassDoorBlock;
import net.mcreator.archiblocktwo.block.BrassChainsBlock;
import net.mcreator.archiblocktwo.block.BrassBlockStairsBlock;
import net.mcreator.archiblocktwo.block.BrassBarsTopBlock;
import net.mcreator.archiblocktwo.block.BrassBarsMiddleBlock;
import net.mcreator.archiblocktwo.block.BrassBarsBottomBlock;
import net.mcreator.archiblocktwo.block.BrassBarsBlock;
import net.mcreator.archiblocktwo.block.BlushRoseShrubBlock;
import net.mcreator.archiblocktwo.block.BlushRoseBushBlock;
import net.mcreator.archiblocktwo.block.BlushRoseBlock;
import net.mcreator.archiblocktwo.block.BlueSpoolBlock;
import net.mcreator.archiblocktwo.block.BlueSlantedShinglesSideBlock;
import net.mcreator.archiblocktwo.block.BlueSlantedClayShinglesBlock;
import net.mcreator.archiblocktwo.block.BlueNeonBlockBlock;
import net.mcreator.archiblocktwo.block.BlueClayShinglesBlock;
import net.mcreator.archiblocktwo.block.BlueClayShingleSlabBlock;
import net.mcreator.archiblocktwo.block.BlueClayBrickTilesBlock;
import net.mcreator.archiblocktwo.block.BlueClayBrickSmallTilesBlock;
import net.mcreator.archiblocktwo.block.BlueClayBrickPavementBlock;
import net.mcreator.archiblocktwo.block.BlueClayBrickBlockBlock;
import net.mcreator.archiblocktwo.block.BlueBigClayBricksBlock;
import net.mcreator.archiblocktwo.block.BlockOfBrassBlock;
import net.mcreator.archiblocktwo.block.BlackSpoolBlock;
import net.mcreator.archiblocktwo.block.BlackNeonBlockBlock;
import net.mcreator.archiblocktwo.block.BirchBasketSandBlock;
import net.mcreator.archiblocktwo.block.BirchBasketPodzolBlock;
import net.mcreator.archiblocktwo.block.BirchBasketMyceliumBlock;
import net.mcreator.archiblocktwo.block.BirchBasketMossBlock;
import net.mcreator.archiblocktwo.block.BirchBasketDirtBlock;
import net.mcreator.archiblocktwo.block.BigNetherBricksBlock;
import net.mcreator.archiblocktwo.block.BigNetherBrickWallBlock;
import net.mcreator.archiblocktwo.block.BigNetherBrickStairsBlock;
import net.mcreator.archiblocktwo.block.BigNetherBrickSlabBlock;
import net.mcreator.archiblocktwo.block.BigClayBricksBlock;
import net.mcreator.archiblocktwo.block.BambooWindChimesBlock;
import net.mcreator.archiblocktwo.block.BambooPlanksBlock;
import net.mcreator.archiblocktwo.block.BambooPlankStairsBlock;
import net.mcreator.archiblocktwo.block.BambooPlankSlabBlock;
import net.mcreator.archiblocktwo.block.BambooPlankFenceGateBlock;
import net.mcreator.archiblocktwo.block.BambooPlankFenceBlock;
import net.mcreator.archiblocktwo.block.BambooLadderBlock;
import net.mcreator.archiblocktwo.block.BambooDreamcatcherBlock;
import net.mcreator.archiblocktwo.block.BambooBasketBlock;
import net.mcreator.archiblocktwo.block.BBlockBlock;
import net.mcreator.archiblocktwo.block.ArchiumVeinsBlock;
import net.mcreator.archiblocktwo.block.ArchiumTendrilsBlock;
import net.mcreator.archiblocktwo.block.ArchiumBlock;
import net.mcreator.archiblocktwo.block.ApostropheBlockBlock;
import net.mcreator.archiblocktwo.block.AndesiteTilesBlock;
import net.mcreator.archiblocktwo.block.AndesiteSmallBricksBlock;
import net.mcreator.archiblocktwo.block.AndesitePillarBlock;
import net.mcreator.archiblocktwo.block.AndesiteBricksBlock;
import net.mcreator.archiblocktwo.block.AndesiteBrickWallBlock;
import net.mcreator.archiblocktwo.block.AndesiteBrickStairsBlock;
import net.mcreator.archiblocktwo.block.AndesiteBrickSlabBlock;
import net.mcreator.archiblocktwo.block.AndesiteBlockWallBlock;
import net.mcreator.archiblocktwo.block.AndesiteBlockStairsBlock;
import net.mcreator.archiblocktwo.block.AndesiteBlockSlabBlock;
import net.mcreator.archiblocktwo.block.AndesiteBlockBlock;
import net.mcreator.archiblocktwo.block.AcaciaBasketSandBlock;
import net.mcreator.archiblocktwo.block.AcaciaBasketPodzolBlock;
import net.mcreator.archiblocktwo.block.AcaciaBasketMyceliumBlock;
import net.mcreator.archiblocktwo.block.AcaciaBasketMossBlock;
import net.mcreator.archiblocktwo.block.AcaciaBasketDirtBlock;
import net.mcreator.archiblocktwo.block.ABlockBlock;

import java.util.List;
import java.util.ArrayList;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class ArchiblockTwoModBlocks {
	private static final List<Block> REGISTRY = new ArrayList<>();
	public static final Block ANDESITE_BLOCK = register(new AndesiteBlockBlock());
	public static final Block ANDESITE_BRICKS = register(new AndesiteBricksBlock());
	public static final Block ANDESITE_SMALL_BRICKS = register(new AndesiteSmallBricksBlock());
	public static final Block ANDESITE_PILLAR = register(new AndesitePillarBlock());
	public static final Block ANDESITE_TILES = register(new AndesiteTilesBlock());
	public static final Block CHISELLED_ANDESITE = register(new ChiselledAndesiteBlock());
	public static final Block ANDESITE_BLOCK_STAIRS = register(new AndesiteBlockStairsBlock());
	public static final Block ANDESITE_BLOCK_SLAB = register(new AndesiteBlockSlabBlock());
	public static final Block ANDESITE_BRICK_STAIRS = register(new AndesiteBrickStairsBlock());
	public static final Block ANDESITE_BRICK_SLAB = register(new AndesiteBrickSlabBlock());
	public static final Block ANDESITE_BLOCK_WALL = register(new AndesiteBlockWallBlock());
	public static final Block ANDESITE_BRICK_WALL = register(new AndesiteBrickWallBlock());
	public static final Block CUT_GRANITE = register(new CutGraniteBlock());
	public static final Block GRANITE_BRICKS = register(new GraniteBricksBlock());
	public static final Block GRANITE_TILES = register(new GraniteTilesBlock());
	public static final Block CHISELLED_GRANITE = register(new ChiselledGraniteBlock());
	public static final Block GRANITE_PILLAR = register(new GranitePillarBlock());
	public static final Block GRANITE_CUT_PILLAR = register(new GraniteCutPillarBlock());
	public static final Block GRANITE_SMALL_BRICKS = register(new GraniteSmallBricksBlock());
	public static final Block CUT_GRANITE_STAIRS = register(new CutGraniteStairsBlock());
	public static final Block CUT_GRANITE_SLAB = register(new CutGraniteSlabBlock());
	public static final Block CUT_GRANITE_WALL = register(new CutGraniteWallBlock());
	public static final Block GRANITE_BRICK_STAIRS = register(new GraniteBrickStairsBlock());
	public static final Block GRANITE_BRICK_SLAB = register(new GraniteBrickSlabBlock());
	public static final Block GRANITE_BRICK_WALL = register(new GraniteBrickWallBlock());
	public static final Block CUT_DIORITE = register(new CutDioriteBlock());
	public static final Block DIORITE_BRICKS = register(new DioriteBricksBlock());
	public static final Block DIORITE_BRICK_STAIRS = register(new DioriteBrickStairsBlock());
	public static final Block DIORITE_BRICK_SLAB = register(new DioriteBrickSlabBlock());
	public static final Block DIORITE_BRICK_WALL = register(new DioriteBrickWallBlock());
	public static final Block DIORITE_TILES = register(new DioriteTilesBlock());
	public static final Block DIORITE_PILLAR = register(new DioritePillarBlock());
	public static final Block FANCY_DIORITE_PILLAR = register(new FancyDioritePillarBlock());
	public static final Block CHISELLED_DIORITE = register(new ChiselledDioriteBlock());
	public static final Block DIORITE_TILE_STAIRS = register(new DioriteTileStairsBlock());
	public static final Block DIORITE_TILE_SLAB = register(new DioriteTileSlabBlock());
	public static final Block DIORITE_TILE_WALL = register(new DioriteTileWallBlock());
	public static final Block RED_SPOOL = register(new RedSpoolBlock());
	public static final Block ORANGE_SPOOL = register(new OrangeSpoolBlock());
	public static final Block YELLOW_SPOOL = register(new YellowSpoolBlock());
	public static final Block PINK_SPOOL = register(new PinkSpoolBlock());
	public static final Block MAGENTA_SPOOL = register(new MagentaSpoolBlock());
	public static final Block PURPLE_SPOOL = register(new PurpleSpoolBlock());
	public static final Block BLUE_SPOOL = register(new BlueSpoolBlock());
	public static final Block CYAN_SPOOL = register(new CyanSpoolBlock());
	public static final Block LIGHT_BLUE_SPOOL = register(new LightBlueSpoolBlock());
	public static final Block LIME_SPOOL = register(new LimeSpoolBlock());
	public static final Block GREEN_SPOOL = register(new GreenSpoolBlock());
	public static final Block BROWN_SPOOL = register(new BrownSpoolBlock());
	public static final Block BLACK_SPOOL = register(new BlackSpoolBlock());
	public static final Block GRAY_SPOOL = register(new GraySpoolBlock());
	public static final Block LIGHT_GRAY_SPOOL = register(new LightGraySpoolBlock());
	public static final Block WHITE_SPOOL = register(new WhiteSpoolBlock());
	public static final Block CUT_STONE = register(new CutStoneBlock());
	public static final Block CUT_STONE_STAIRS = register(new CutStoneStairsBlock());
	public static final Block CUT_STONE_SLAB = register(new CutStoneSlabBlock());
	public static final Block CUT_STONE_WALL = register(new CutStoneWallBlock());
	public static final Block SMALL_STONE_BRICKS = register(new SmallStoneBricksBlock());
	public static final Block STONE_PILLAR = register(new StonePillarBlock());
	public static final Block STONE_TILES = register(new StoneTilesBlock());
	public static final Block CRACKED_CUT_STONE = register(new CrackedCutStoneBlock());
	public static final Block MOSSY_CRACKED_STONE = register(new MossyCrackedStoneBlock());
	public static final Block MOSSY_SMALL_STONE_BRICKS = register(new MossySmallStoneBricksBlock());
	public static final Block CRACKED_STONE_PILLAR = register(new CrackedStonePillarBlock());
	public static final Block MOSSY_STONE_PILLAR = register(new MossyStonePillarBlock());
	public static final Block CRACKED_STONE_TILES = register(new CrackedStoneTilesBlock());
	public static final Block MOSSY_STONE_TILES = register(new MossyStoneTilesBlock());
	public static final Block SNOWY_STONE = register(new SnowyStoneBlock());
	public static final Block SNOWY_STONE_STAIRS = register(new SnowyStoneStairsBlock());
	public static final Block SNOWY_STONE_SLAB = register(new SnowyStoneSlabBlock());
	public static final Block SNOWY_COBBLESTONE = register(new SnowyCobblestoneBlock());
	public static final Block SNOWY_COBBLESTONE_STAIRS = register(new SnowyCobblestoneStairsBlock());
	public static final Block SNOWY_COBBLESTONE_SLAB = register(new SnowyCobblestoneSlabBlock());
	public static final Block SNOWY_CUT_STONE = register(new SnowyCutStoneBlock());
	public static final Block SNOWY_CUT_STONE_STAIRS = register(new SnowyCutStoneStairsBlock());
	public static final Block SNOWY_CUT_STONE_SLAB = register(new SnowyCutStoneSlabBlock());
	public static final Block SNOWY_STONE_BRICKS = register(new SnowyStoneBricksBlock());
	public static final Block SNOWY_STONE_BRICK_STAIRS = register(new SnowyStoneBrickStairsBlock());
	public static final Block SNOWY_STONE_BRICK_SLAB = register(new SnowyStoneBrickSlabBlock());
	public static final Block SNOWY_STONE_TILES = register(new SnowyStoneTilesBlock());
	public static final Block SNOWY_SMALL_STONE_BRICKS = register(new SnowySmallStoneBricksBlock());
	public static final Block SNOWY_STONE_PILLAR = register(new SnowyStonePillarBlock());
	public static final Block SNOWY_CHISELLED_STONE_BRICKS = register(new SnowyChiselledStoneBricksBlock());
	public static final Block BIG_CLAY_BRICKS = register(new BigClayBricksBlock());
	public static final Block CLAY_BRICK_BLOCK = register(new ClayBrickBlockBlock());
	public static final Block CLAY_BRICK_TILES = register(new ClayBrickTilesBlock());
	public static final Block SMALL_CLAY_BRICK_TILES = register(new SmallClayBrickTilesBlock());
	public static final Block CLAY_BRICK_PAVEMENT = register(new ClayBrickPavementBlock());
	public static final Block CLAY_SHINGLES = register(new ClayShinglesBlock());
	public static final Block SLANTED_CLAY_SHINGLES = register(new SlantedClayShinglesBlock());
	public static final Block SLANTED_SHINGLES_SIDE = register(new SlantedShinglesSideBlock());
	public static final Block RED_BIG_CLAY_BRICKS = register(new RedBigClayBricksBlock());
	public static final Block RED_CLAY_BRICK_BLOCK = register(new RedClayBrickBlockBlock());
	public static final Block RED_CLAY_BRICK_TILES = register(new RedClayBrickTilesBlock());
	public static final Block RED_CLAY_BRICK_SMALL_TILES = register(new RedClayBrickSmallTilesBlock());
	public static final Block RED_CLAY_BRICK_PAVEMENT = register(new RedClayBrickPavementBlock());
	public static final Block RED_CLAY_SHINGLES = register(new RedClayShinglesBlock());
	public static final Block RED_CLAY_SHINGLES_SLAB = register(new RedClayShinglesSlabBlock());
	public static final Block RED_SLANTED_SHINGLES_SIDE = register(new RedSlantedShinglesSideBlock());
	public static final Block RED_SLANTED_CLAY_SHINGLES = register(new RedSlantedClayShinglesBlock());
	public static final Block BLUE_CLAY_BRICK_BLOCK = register(new BlueClayBrickBlockBlock());
	public static final Block BLUE_BIG_CLAY_BRICKS = register(new BlueBigClayBricksBlock());
	public static final Block BLUE_CLAY_BRICK_TILES = register(new BlueClayBrickTilesBlock());
	public static final Block BLUE_CLAY_BRICK_SMALL_TILES = register(new BlueClayBrickSmallTilesBlock());
	public static final Block BLUE_CLAY_BRICK_PAVEMENT = register(new BlueClayBrickPavementBlock());
	public static final Block BLUE_CLAY_SHINGLES = register(new BlueClayShinglesBlock());
	public static final Block BLUE_CLAY_SHINGLE_SLAB = register(new BlueClayShingleSlabBlock());
	public static final Block BLUE_SLANTED_CLAY_SHINGLES = register(new BlueSlantedClayShinglesBlock());
	public static final Block BLUE_SLANTED_SHINGLES_SIDE = register(new BlueSlantedShinglesSideBlock());
	public static final Block WOVEN_BIRCH_BLOCK = register(new WovenBirchBlockBlock());
	public static final Block WOVEN_BIRCH_STAIRS = register(new WovenBirchStairsBlock());
	public static final Block WOVEN_BIRCH_SLAB = register(new WovenBirchSlabBlock());
	public static final Block WOVEN_BIRCH_BASKET = register(new WovenBirchBasketBlock());
	public static final Block BIRCH_BASKET_DIRT = register(new BirchBasketDirtBlock());
	public static final Block BIRCH_BASKET_MOSS = register(new BirchBasketMossBlock());
	public static final Block BIRCH_BASKET_MYCELIUM = register(new BirchBasketMyceliumBlock());
	public static final Block BIRCH_BASKET_PODZOL = register(new BirchBasketPodzolBlock());
	public static final Block BIRCH_BASKET_SAND = register(new BirchBasketSandBlock());
	public static final Block WOVEN_BASKET = register(new WovenBasketBlock());
	public static final Block WOVEN_FIBER_BLOCK = register(new WovenFiberBlockBlock());
	public static final Block WOVEN_FIBER_STAIRS = register(new WovenFiberStairsBlock());
	public static final Block WOVEN_FIBER_SLAB = register(new WovenFiberSlabBlock());
	public static final Block WOVEN_BASKET_DIRT = register(new WovenBasketDirtBlock());
	public static final Block WOVEN_BASKET_GRASS = register(new WovenBasketGrassBlock());
	public static final Block WOVEN_BASKET_MYCELIUM = register(new WovenBasketMyceliumBlock());
	public static final Block WOVEN_BASKET_PODZOL = register(new WovenBasketPodzolBlock());
	public static final Block WOVEN_BASKET_SAND = register(new WovenBasketSandBlock());
	public static final Block WOVEN_SPRUCE_BLOCK = register(new WovenSpruceBlockBlock());
	public static final Block WOVEN_SPRUCE_STAIRS = register(new WovenSpruceStairsBlock());
	public static final Block WOVEN_SPRUCE_SLAB = register(new WovenSpruceSlabBlock());
	public static final Block WOVEN_SPRUCE_BASKET = register(new WovenSpruceBasketBlock());
	public static final Block SPRUCE_BASKET_DIRT = register(new SpruceBasketDirtBlock());
	public static final Block SPRUCE_BASKET_MOSS = register(new SpruceBasketMossBlock());
	public static final Block SPRUCE_BASKET_PODZOL = register(new SpruceBasketPodzolBlock());
	public static final Block SPRUCE_BASKET_MYCELIUM = register(new SpruceBasketMyceliumBlock());
	public static final Block SPRUCE_BASKET_SAND = register(new SpruceBasketSandBlock());
	public static final Block WOVEN_DARK_OAK_BLOCK = register(new WovenDarkOakBlockBlock());
	public static final Block WOVEN_DARK_OAK_STAIRS = register(new WovenDarkOakStairsBlock());
	public static final Block WOVEN_DARK_OAK_SLAB = register(new WovenDarkOakSlabBlock());
	public static final Block WOVEN_DARK_OAK_BASKET = register(new WovenDarkOakBasketBlock());
	public static final Block DARK_OAK_BASKET_DIRT = register(new DarkOakBasketDirtBlock());
	public static final Block DARK_OAK_BASKET_MOSS = register(new DarkOakBasketMossBlock());
	public static final Block CLAY_SHINGLES_SLAB = register(new ClayShinglesSlabBlock());
	public static final Block DARK_OAK_BASKET_PODZOL = register(new DarkOakBasketPodzolBlock());
	public static final Block DARK_OAK_BASKET_MYCELIUM = register(new DarkOakBasketMyceliumBlock());
	public static final Block DARK_OAK_BASKET_SAND = register(new DarkOakBasketSandBlock());
	public static final Block WOVEN_JUNGLE_BLOCK = register(new WovenJungleBlockBlock());
	public static final Block WOVEN_JUNGLE_STAIRS = register(new WovenJungleStairsBlock());
	public static final Block WOVEN_JUNGLE_SLAB = register(new WovenJungleSlabBlock());
	public static final Block WOVEN_JUNGLE_BASKET = register(new WovenJungleBasketBlock());
	public static final Block JUNGLE_BASKET_DIRT = register(new JungleBasketDirtBlock());
	public static final Block JUNGLE_BASKET_MOSS = register(new JungleBasketMossBlock());
	public static final Block JUNGLE_BASKET_PODZOL = register(new JungleBasketPodzolBlock());
	public static final Block JUNGLE_BASKET_MYCELIUM = register(new JungleBasketMyceliumBlock());
	public static final Block JUNGLE_BASKET_SAND = register(new JungleBasketSandBlock());
	public static final Block WOVEN_ACACIA_BLOCK = register(new WovenAcaciaBlockBlock());
	public static final Block WOVEN_ACACIA_STAIRS = register(new WovenAcaciaStairsBlock());
	public static final Block WOVEN_ACACIA_SLAB = register(new WovenAcaciaSlabBlock());
	public static final Block WOVEN_ACACIA_BASKET = register(new WovenAcaciaBasketBlock());
	public static final Block ACACIA_BASKET_DIRT = register(new AcaciaBasketDirtBlock());
	public static final Block ACACIA_BASKET_MOSS = register(new AcaciaBasketMossBlock());
	public static final Block ACACIA_BASKET_MYCELIUM = register(new AcaciaBasketMyceliumBlock());
	public static final Block ACACIA_BASKET_PODZOL = register(new AcaciaBasketPodzolBlock());
	public static final Block ACACIA_BASKET_SAND = register(new AcaciaBasketSandBlock());
	public static final Block WOVEN_CRIMSON_BASKET = register(new WovenCrimsonBasketBlock());
	public static final Block WOVEN_CRIMSON_BLOCK = register(new WovenCrimsonBlockBlock());
	public static final Block WOVEN_CRIMSON_STAIRS = register(new WovenCrimsonStairsBlock());
	public static final Block WOVEN_CRIMSON_SLAB = register(new WovenCrimsonSlabBlock());
	public static final Block CRIMSON_BASKET_DIRT = register(new CrimsonBasketDirtBlock());
	public static final Block CRIMSON_BASKET_MOSS = register(new CrimsonBasketMossBlock());
	public static final Block CRIMSON_BASKET_PODZOL = register(new CrimsonBasketPodzolBlock());
	public static final Block CRIMSON_BASKET_MYCELIUM = register(new CrimsonBasketMyceliumBlock());
	public static final Block CRIMSON_BASKET_SAND = register(new CrimsonBasketSandBlock());
	public static final Block WOVEN_WARPED_BLOCK = register(new WovenWarpedBlockBlock());
	public static final Block WOVEN_WARPED_STAIRS = register(new WovenWarpedStairsBlock());
	public static final Block WOVEN_WARPED_SLAB = register(new WovenWarpedSlabBlock());
	public static final Block WOVEN_WARPED_BASKET = register(new WovenWarpedBasketBlock());
	public static final Block WARPED_BASKET_DIRT = register(new WarpedBasketDirtBlock());
	public static final Block WARPED_BASKET_MOSS = register(new WarpedBasketMossBlock());
	public static final Block WARPED_BASKET_PODZOL = register(new WarpedBasketPodzolBlock());
	public static final Block WARPED_BASKET_MYCELIUM = register(new WarpedBasketMyceliumBlock());
	public static final Block WARPED_BASKET_SAND = register(new WarpedBasketSandBlock());
	public static final Block WOVEN_MYSTIC_MAPLE_BLOCK = register(new WovenMysticMapleBlockBlock());
	public static final Block WOVEN_MYSTIC_MAPLE_STAIRS = register(new WovenMysticMapleStairsBlock());
	public static final Block WOVEN_MYSTIC_MAPLE_SLAB = register(new WovenMysticMapleSlabBlock());
	public static final Block WOVEN_MYSTIC_MAPLE_BASKET = register(new WovenMysticMapleBasketBlock());
	public static final Block MYSTIC_BASKET_DIRT = register(new MysticBasketDirtBlock());
	public static final Block MYSTIC_BASKET_MOSS = register(new MysticBasketMossBlock());
	public static final Block MYSTIC_BASKET_PODZOL = register(new MysticBasketPodzolBlock());
	public static final Block MYSTIC_BASKET_MYCELIUM = register(new MysticBasketMyceliumBlock());
	public static final Block MYSTIC_BASKET_SAND = register(new MysticBasketSandBlock());
	public static final Block CUT_OBSIDIAN = register(new CutObsidianBlock());
	public static final Block OBSIDIAN_BRICKS = register(new ObsidianBricksBlock());
	public static final Block SMALL_OBSIDIAN_BRICKS = register(new SmallObsidianBricksBlock());
	public static final Block OBSIDIAN_TILES = register(new ObsidianTilesBlock());
	public static final Block CHISELLED_OBSIDIAN = register(new ChiselledObsidianBlock());
	public static final Block OBSIDIAN_PILLAR = register(new ObsidianPillarBlock());
	public static final Block OBSIDIAN_BRICK_STAIRS = register(new ObsidianBrickStairsBlock());
	public static final Block OBSIDIAN_BRICK_SLAB = register(new ObsidianBrickSlabBlock());
	public static final Block OBSIDIAN_BRICK_WALL = register(new ObsidianBrickWallBlock());
	public static final Block CHISELLED_OBSIDIAN_STAIRS = register(new ChiselledObsidianStairsBlock());
	public static final Block CHISELLED_OBSIDIAN_SLAB = register(new ChiselledObsidianSlabBlock());
	public static final Block CHISELLED_OBSIDIAN_WALL = register(new ChiselledObsidianWallBlock());
	public static final Block ROSE_QUARTZ_ORE = register(new RoseQuartzOreBlock());
	public static final Block ROSE_QUARTZ_BLOCK = register(new RoseQuartzBlockBlock());
	public static final Block ROSE_QUARTZ_BRICKS = register(new RoseQuartzBricksBlock());
	public static final Block ROSE_QUARTZ_BRICK_STAIRS = register(new RoseQuartzBrickStairsBlock());
	public static final Block ROSE_BRICK_SLAB = register(new RoseBrickSlabBlock());
	public static final Block ROSE_QUARTZ_BRICKS_2 = register(new RoseQuartzBricks2Block());
	public static final Block ROSE_BRICK_STAIRS_2 = register(new RoseBrickStairs2Block());
	public static final Block ROSE_BRICK_SLAB_2 = register(new RoseBrickSlab2Block());
	public static final Block ROSE_BRICK_WALL_2 = register(new RoseBrickWall2Block());
	public static final Block ROSE_BRICK_WALL = register(new RoseBrickWallBlock());
	public static final Block ROSE_QUARTZ_SLAB = register(new RoseQuartzSlabBlock());
	public static final Block ROSE_QUARTZ_STAIRS = register(new RoseQuartzStairsBlock());
	public static final Block ROSE_QUARTZ_WALL = register(new RoseQuartzWallBlock());
	public static final Block SMOOTH_ROSE_QUARTZ = register(new SmoothRoseQuartzBlock());
	public static final Block SMOOTH_ROSE_QUARTZ_STAIRS = register(new SmoothRoseQuartzStairsBlock());
	public static final Block SMOOTH_ROSE_QUARTZ_SLAB = register(new SmoothRoseQuartzSlabBlock());
	public static final Block SMOOTH_ROSE_QUARTZ_WALL = register(new SmoothRoseQuartzWallBlock());
	public static final Block ROSE_QUARTZ_PILLAR = register(new RoseQuartzPillarBlock());
	public static final Block CHISELLED_ROSE_QUARTZ = register(new ChiselledRoseQuartzBlock());
	public static final Block SMOKY_QUARTZ_ORE = register(new SmokyQuartzOreBlock());
	public static final Block SMOKY_QUARTZ_BLOCK = register(new SmokyQuartzBlockBlock());
	public static final Block SMOKY_QUARTZ_BRICKS = register(new SmokyQuartzBricksBlock());
	public static final Block SMOKY_BRICK_STAIRS = register(new SmokyBrickStairsBlock());
	public static final Block SMOKY_BRICK_SLAB = register(new SmokyBrickSlabBlock());
	public static final Block SMOKY_QUARTZ_BRICKS_2 = register(new SmokyQuartzBricks2Block());
	public static final Block SMOKY_STAIRS_2 = register(new SmokyStairs2Block());
	public static final Block SMOKY_SLAB_2 = register(new SmokySlab2Block());
	public static final Block SMOKY_WALL_2 = register(new SmokyWall2Block());
	public static final Block SMOKY_BRICK_WALL = register(new SmokyBrickWallBlock());
	public static final Block SMOKY_QUARTZ_STAIRS = register(new SmokyQuartzStairsBlock());
	public static final Block SMOKY_QUARTZ_SLAB = register(new SmokyQuartzSlabBlock());
	public static final Block SMOKY_QUARTZ_WALL = register(new SmokyQuartzWallBlock());
	public static final Block SMOOTH_SMOKY_QUARTZ = register(new SmoothSmokyQuartzBlock());
	public static final Block SMOOTH_SMOKY_QUARTZ_STAIRS = register(new SmoothSmokyQuartzStairsBlock());
	public static final Block SMOOTH_SMOKY_QUARTZ_SLAB = register(new SmoothSmokyQuartzSlabBlock());
	public static final Block SMOOTH_SMOKY_QUARTZ_WALL = register(new SmoothSmokyQuartzWallBlock());
	public static final Block SMOKY_QUARTZ_PILLAR = register(new SmokyQuartzPillarBlock());
	public static final Block CHISELLED_SMOKY_QUARTZ = register(new ChiselledSmokyQuartzBlock());
	public static final Block TOPAZ_STONE_ORE = register(new TopazStoneOreBlock());
	public static final Block TOPAZ_GRANITE_ORE = register(new TopazGraniteOreBlock());
	public static final Block TOPAZ_BLOCK = register(new TopazBlockBlock());
	public static final Block TOPAZ_BRICKS = register(new TopazBricksBlock());
	public static final Block TOPAZ_TILES = register(new TopazTilesBlock());
	public static final Block TOPAZ_PILLARS = register(new TopazPillarsBlock());
	public static final Block RUBY_ORE = register(new RubyOreBlock());
	public static final Block RUBY_BLOCK = register(new RubyBlockBlock());
	public static final Block RUBY_BRICKS = register(new RubyBricksBlock());
	public static final Block RUBY_TILES = register(new RubyTilesBlock());
	public static final Block RUBY_PILLAR = register(new RubyPillarBlock());
	public static final Block SAPPHIRE_DIORITE_ORE = register(new SapphireDioriteOreBlock());
	public static final Block SAPPHIRE_ORE = register(new SapphireOreBlock());
	public static final Block SAPPHIRE_BLOCK = register(new SapphireBlockBlock());
	public static final Block SAPPHIRE_BRICKS = register(new SapphireBricksBlock());
	public static final Block SAPPHIRE_TILES = register(new SapphireTilesBlock());
	public static final Block SAPPHIRE_PILLAR = register(new SapphirePillarBlock());
	public static final Block SUGILITE_ORE = register(new SugiliteOreBlock());
	public static final Block SUGILITE_BLOCK = register(new SugiliteBlockBlock());
	public static final Block SUGILITE_TILES = register(new SugiliteTilesBlock());
	public static final Block SUGILITE_PILLAR = register(new SugilitePillarBlock());
	public static final Block TWILIGHT_ORE = register(new TwilightOreBlock());
	public static final Block TWILIGHT_BLOCK = register(new TwilightBlockBlock());
	public static final Block RAW_TWILIGHT_BLOCK = register(new RawTwilightBlockBlock());
	public static final Block TWILIGHT_BRICKS = register(new TwilightBricksBlock());
	public static final Block TWILIGHT_TILES = register(new TwilightTilesBlock());
	public static final Block CHISELLED_TWILIGHT_BRICKS = register(new ChiselledTwilightBricksBlock());
	public static final Block TWILIGHT_PILLAR = register(new TwilightPillarBlock());
	public static final Block TWILIGHT_PILLAR_TOP = register(new TwilightPillarTopBlock());
	public static final Block TWILIGHT_BRICK_SLAB = register(new TwilightBrickSlabBlock());
	public static final Block TWILIGHT_BRICK_STAIRS = register(new TwilightBrickStairsBlock());
	public static final Block TWILIGHT_BRICK_WALL = register(new TwilightBrickWallBlock());
	public static final Block RAW_LUSH_TWILIGHT_BLOCK = register(new RawLushTwilightBlockBlock());
	public static final Block LUSH_TWILIGHT_BLOCK = register(new LushTwilightBlockBlock());
	public static final Block LUSH_TWILIGHT_BRICKS = register(new LushTwilightBricksBlock());
	public static final Block LUSH_TWILIGHT_TILES = register(new LushTwilightTilesBlock());
	public static final Block LUSH_TWILIGHT_PILLAR = register(new LushTwilightPillarBlock());
	public static final Block LUSH_TWILIGHT_PILLAR_TOP = register(new LushTwilightPillarTopBlock());
	public static final Block CHISELLED_LUSH_TWILIGHT_BRICKS = register(new ChiselledLushTwilightBricksBlock());
	public static final Block LUSH_TWILIGHT_BRICK_SLAB = register(new LushTwilightBrickSlabBlock());
	public static final Block LUSH_TWILIGHT_BRICK_STAIRS = register(new LushTwilightBrickStairsBlock());
	public static final Block LUSH_TWILIGHT_BRICK_WALL = register(new LushTwilightBrickWallBlock());
	public static final Block RAW_TWILIGHTWAVE_BLOCK = register(new RawTwilightwaveBlockBlock());
	public static final Block TWILIGHTWAVE_BLOCK = register(new TwilightwaveBlockBlock());
	public static final Block TWILIGHTWAVE_BRICKS = register(new TwilightwaveBricksBlock());
	public static final Block TWILIGHTWAVE_TILES = register(new TwilightwaveTilesBlock());
	public static final Block CHISELLED_TWILIGHTWAVE_BRICKS = register(new ChiselledTwilightwaveBricksBlock());
	public static final Block TWILIGHTWAVE_PILLAR = register(new TwilightwavePillarBlock());
	public static final Block TWILIGHTWAVE_PILLAR_TOP = register(new TwilightwavePillarTopBlock());
	public static final Block TWILIGHTWAVE_BRICK_STAIRS = register(new TwilightwaveBrickStairsBlock());
	public static final Block TWILIGHTWAVE_BRICK_SLAB = register(new TwilightwaveBrickSlabBlock());
	public static final Block TWILIGHTWAVE_BRICK_WALL = register(new TwilightwaveBrickWallBlock());
	public static final Block SUGILITE_BRICKS = register(new SugiliteBricksBlock());
	public static final Block PITCHDARK_BLOCK = register(new PitchdarkBlockBlock());
	public static final Block GLOWING_EYES_DOTS = register(new GlowingEyesDotsBlock());
	public static final Block GLOWING_EYES_ROUND_BLINK = register(new GlowingEyesRoundBlinkBlock());
	public static final Block GLOWING_EYES_ROUND_STARE = register(new GlowingEyesRoundStareBlock());
	public static final Block WHITE_NEON_BLOCK = register(new WhiteNeonBlockBlock());
	public static final Block GRAY_NEON_BLOCK = register(new GrayNeonBlockBlock());
	public static final Block LIGHT_GRAY_NEON_BLOCK = register(new LightGrayNeonBlockBlock());
	public static final Block BLACK_NEON_BLOCK = register(new BlackNeonBlockBlock());
	public static final Block RED_NEON_BLOCK = register(new RedNeonBlockBlock());
	public static final Block ORANGE_NEON_BLOCK = register(new OrangeNeonBlockBlock());
	public static final Block YELLOW_NEON_BLOCK = register(new YellowNeonBlockBlock());
	public static final Block LIME_NEON_BLOCK = register(new LimeNeonBlockBlock());
	public static final Block CYAN_NEON_BLOCK = register(new CyanNeonBlockBlock());
	public static final Block LIGHT_BLUE_NEON_BLOCK = register(new LightBlueNeonBlockBlock());
	public static final Block BLUE_NEON_BLOCK = register(new BlueNeonBlockBlock());
	public static final Block PURPLE_NEON_BLOCK = register(new PurpleNeonBlockBlock());
	public static final Block MAGENTA_NEON_BLOCK = register(new MagentaNeonBlockBlock());
	public static final Block PINK_NEON_BLOCK = register(new PinkNeonBlockBlock());
	public static final Block BROWN_NEON_BLOCK = register(new BrownNeonBlockBlock());
	public static final Block GREEN_NEON_BLOCK = register(new GreenNeonBlockBlock());
	public static final Block BLOCK_OF_BRASS = register(new BlockOfBrassBlock());
	public static final Block CUT_BRASS_SLAB = register(new CutBrassSlabBlock());
	public static final Block DENTED_BRASS_TILES = register(new DentedBrassTilesBlock());
	public static final Block DENTED_BRASS_TILE_SLAB = register(new DentedBrassTileSlabBlock());
	public static final Block HALF_DENTED_BRASS_TILES = register(new HalfDentedBrassTilesBlock());
	public static final Block HALF_DENTED_BRASS_T_ILE_SLAB = register(new HalfDentedBrassTIleSlabBlock());
	public static final Block BRASS_TILES_R = register(new BrassTilesRBlock());
	public static final Block BRASS_TILE_SLAB = register(new BrassTileSlabBlock());
	public static final Block BRASS_DOOR = register(new BrassDoorBlock());
	public static final Block BRASS_TRAPDOOR = register(new BrassTrapdoorBlock());
	public static final Block BRASS_CHAINS = register(new BrassChainsBlock());
	public static final Block BRASS_PIPE = register(new BrassPipeBlock());
	public static final Block BRASS_BARS_MIDDLE = register(new BrassBarsMiddleBlock());
	public static final Block STRING_MESH = register(new StringMeshBlock());
	public static final Block FRAMED_STRING_MESH = register(new FramedStringMeshBlock());
	public static final Block ROSE = register(new RoseBlock());
	public static final Block ROSE_SHRUB = register(new RoseShrubBlock());
	public static final Block SCARLET_ROSE = register(new ScarletRoseBlock());
	public static final Block SCARLET_ROSE_BUSH = register(new ScarletRoseBushBlock());
	public static final Block SCARLET_ROSE_SHRUB = register(new ScarletRoseShrubBlock());
	public static final Block BLUSH_ROSE = register(new BlushRoseBlock());
	public static final Block BLUSH_ROSE_SHRUB = register(new BlushRoseShrubBlock());
	public static final Block BLUSH_ROSE_BUSH = register(new BlushRoseBushBlock());
	public static final Block PINK_ROSE = register(new PinkRoseBlock());
	public static final Block PINK_ROSE_SHRUB = register(new PinkRoseShrubBlock());
	public static final Block PINK_ROSE_BUSH = register(new PinkRoseBushBlock());
	public static final Block BUTTERMILK_ROSE = register(new ButtermilkRoseBlock());
	public static final Block BUTTERMILK_ROSE_BUSH = register(new ButtermilkRoseBushBlock());
	public static final Block BUTTERMILK_ROSE_SHRUB = register(new ButtermilkRoseShrubBlock());
	public static final Block OLIVE_ROSE = register(new OliveRoseBlock());
	public static final Block OLIVE_ROSE_SHRUB = register(new OliveRoseShrubBlock());
	public static final Block OLIVE_ROSE_BUSH = register(new OliveRoseBushBlock());
	public static final Block MYSTIC_MAPLE_WOOD = register(new MysticMapleWoodBlock());
	public static final Block MYSTIC_MAPLE_LOG = register(new MysticMapleLogBlock());
	public static final Block STRIPPED_MYSTIC_MAPLE_WOOD = register(new StrippedMysticMapleWoodBlock());
	public static final Block STRIPPED_MYSTIC_MAPLE_LOG = register(new StrippedMysticMapleLogBlock());
	public static final Block MYSTIC_MAPLE_PLANKS = register(new MysticMaplePlanksBlock());
	public static final Block MYSTIC_MAPLE_STAIRS = register(new MysticMapleStairsBlock());
	public static final Block MYSTIC_MAPLE_SLAB = register(new MysticMapleSlabBlock());
	public static final Block MYSTIC_MAPLE_TRAPDOOR = register(new MysticMapleTrapdoorBlock());
	public static final Block MYSTIC_MAPLE_DOOR = register(new MysticMapleDoorBlock());
	public static final Block MYSTIC_MAPLE_FENCE = register(new MysticMapleFenceBlock());
	public static final Block MYSTIC_MAPLE_FENCE_GATE = register(new MysticMapleFenceGateBlock());
	public static final Block MYSTIC_MAPLE_PRESSURE_PLATE = register(new MysticMaplePressurePlateBlock());
	public static final Block MYSTIC_MAPLE_BUTTON = register(new MysticMapleButtonBlock());
	public static final Block MYSTIC_MAPLE_LEAVES = register(new MysticMapleLeavesBlock());
	public static final Block MYSTIC_MAPLE_SAPLING = register(new MysticMapleSaplingBlock());
	public static final Block TIEDBAMBOO_BLOCK = register(new TiedbambooBlockBlock());
	public static final Block BAMBOO_PLANKS = register(new BambooPlanksBlock());
	public static final Block CARVED_BAMBOO_PLANKS = register(new CarvedBambooPlanksBlock());
	public static final Block BAMBOO_DREAMCATCHER = register(new BambooDreamcatcherBlock());
	public static final Block BAMBOO_LADDER = register(new BambooLadderBlock());
	public static final Block BAMBOO_PLANK_SLAB = register(new BambooPlankSlabBlock());
	public static final Block BAMBOO_PLANK_STAIRS = register(new BambooPlankStairsBlock());
	public static final Block BAMBOO_PLANK_FENCE = register(new BambooPlankFenceBlock());
	public static final Block BAMBOO_PLANK_FENCE_GATE = register(new BambooPlankFenceGateBlock());
	public static final Block BAMBOO_BASKET = register(new BambooBasketBlock());
	public static final Block BAMBOO_WIND_CHIMES = register(new BambooWindChimesBlock());
	public static final Block DRIED_TIED_BAMBOO_BLOCK = register(new DriedTiedBambooBlockBlock());
	public static final Block DRIED_BAMBOO_PLANKS = register(new DriedBambooPlanksBlock());
	public static final Block DRIED_CARVED_BAMBOO_PLANKS = register(new DriedCarvedBambooPlanksBlock());
	public static final Block DRIED_BAMBOO_DREAMCATCHER = register(new DriedBambooDreamcatcherBlock());
	public static final Block DRIED_BAMBOO_LADDER = register(new DriedBambooLadderBlock());
	public static final Block DRIED_BAMBOO_PLANK_STAIRS = register(new DriedBambooPlankStairsBlock());
	public static final Block DRIED_BAMBOO_PLANK_SLAB = register(new DriedBambooPlankSlabBlock());
	public static final Block DRIED_BAMBOO_PLANK_FENCE = register(new DriedBambooPlankFenceBlock());
	public static final Block DRIED_BAMBOO_PLANK_FENCE_GATE = register(new DriedBambooPlankFenceGateBlock());
	public static final Block DRIED_BAMBOO_BASKET = register(new DriedBambooBasketBlock());
	public static final Block DRIED_BAMBOO_WIND_CHIMES = register(new DriedBambooWindChimesBlock());
	public static final Block DRIED_BAMBOO = register(new DriedBambooBlock());
	public static final Block SIDE_SNOWY_STONE_PILLAR = register(new SideSnowyStonePillarBlock());
	public static final Block BRASS_BARS = register(new BrassBarsBlock());
	public static final Block BRASS_BARS_TOP = register(new BrassBarsTopBlock());
	public static final Block BRASS_BARS_BOTTOM = register(new BrassBarsBottomBlock());
	public static final Block BRASS_BLOCK_STAIRS = register(new BrassBlockStairsBlock());
	public static final Block DENTED_BRASS_BLOCK_STAIRS = register(new DentedBrassBlockStairsBlock());
	public static final Block HALF_DENTED_BRASS_BLOCK_STAIRS = register(new HalfDentedBrassBlockStairsBlock());
	public static final Block BRASS_TILES_STAIRS = register(new BrassTilesStairsBlock());
	public static final Block NETHER_BRICK_PLATE = register(new NetherBrickPlateBlock());
	public static final Block BIG_NETHER_BRICKS = register(new BigNetherBricksBlock());
	public static final Block NETHER_BRICK_TILES = register(new NetherBrickTilesBlock());
	public static final Block NETHER_BRICK_PILLAR = register(new NetherBrickPillarBlock());
	public static final Block CRACKED_NETHER_BRICK_PLATE = register(new CrackedNetherBrickPlateBlock());
	public static final Block CRACKED_BIG_NETHER_BRICKS = register(new CrackedBigNetherBricksBlock());
	public static final Block CRACKED_NETHER_BRICK_TILES = register(new CrackedNetherBrickTilesBlock());
	public static final Block WEEPING_VINE_COVERED_NETHER_BRICK_PLATE = register(new WeepingVineCoveredNetherBrickPlateBlock());
	public static final Block WEEPING_VINE_COVERED_BIG_NETHER_BRICKS = register(new WeepingVineCoveredBigNetherBricksBlock());
	public static final Block WEEPING_VINE_COVERED_NETHER_BRICK_TILES = register(new WeepingVineCoveredNetherBrickTilesBlock());
	public static final Block WEEPING_VINE_COVERED_NETHER_BRICK_PILLAR = register(new WeepingVineCoveredNetherBrickPillarBlock());
	public static final Block WEEPING_VINE_COVERED_NETHER_BRICKS = register(new WeepingVineCoveredNetherBricksBlock());
	public static final Block WEEPING_VINE_COVERED_CHISELLED_NETHER_BRICKS = register(new WeepingVineCoveredChiselledNetherBricksBlock());
	public static final Block TWISTING_VINE_COVERED_NETHER_BRICK_PLATE = register(new TwistingVineCoveredNetherBrickPlateBlock());
	public static final Block TWISTING_VINE_COVERED_NETHER_BRICKS = register(new TwistingVineCoveredNetherBricksBlock());
	public static final Block TWISTING_VINE_COVERED_BIG_NETHER_BRICKS = register(new TwistingVineCoveredBigNetherBricksBlock());
	public static final Block TWISTING_VINE_COVERED_NETHER_BRICK_TILES = register(new TwistingVineCoveredNetherBrickTilesBlock());
	public static final Block TWISTING_VINE_COVERED_NETHER_BRICK_PILLAR = register(new TwistingVineCoveredNetherBrickPillarBlock());
	public static final Block TWISTING_VINE_COVERED_CHISELLED_NETHER_BRICKS = register(new TwistingVineCoveredChiselledNetherBricksBlock());
	public static final Block NETHER_BRICK_PLATE_STAIRS = register(new NetherBrickPlateStairsBlock());
	public static final Block NETHER_BRICK_PLATE_SLAB = register(new NetherBrickPlateSlabBlock());
	public static final Block NETHER_BRICK_PLATE_WALL = register(new NetherBrickPlateWallBlock());
	public static final Block BIG_NETHER_BRICK_STAIRS = register(new BigNetherBrickStairsBlock());
	public static final Block BIG_NETHER_BRICK_SLAB = register(new BigNetherBrickSlabBlock());
	public static final Block BIG_NETHER_BRICK_WALL = register(new BigNetherBrickWallBlock());
	public static final Block NETHER_BRICK_TILE_STAIRS = register(new NetherBrickTileStairsBlock());
	public static final Block NETHER_BRICK_TILE_SLAB = register(new NetherBrickTileSlabBlock());
	public static final Block NETHER_BRICK_TILE_WALL = register(new NetherBrickTileWallBlock());
	public static final Block ARCHIUM = register(new ArchiumBlock());
	public static final Block TILED_ARCHIUM = register(new TiledArchiumBlock());
	public static final Block ARCHIUM_VEINS = register(new ArchiumVeinsBlock());
	public static final Block ARCHIUM_TENDRILS = register(new ArchiumTendrilsBlock());
	public static final Block EMPTIED_ARCHIUM = register(new EmptiedArchiumBlock());
	public static final Block A_BLOCK = register(new ABlockBlock());
	public static final Block B_BLOCK = register(new BBlockBlock());
	public static final Block C_BLOCK = register(new CBlockBlock());
	public static final Block D_BLOCK = register(new DBlockBlock());
	public static final Block E_BLOCK = register(new EBlockBlock());
	public static final Block F_BLOCK = register(new FBlockBlock());
	public static final Block G_BLOCK = register(new GBlockBlock());
	public static final Block H_BLOCK = register(new HBlockBlock());
	public static final Block I_BLOCK = register(new IBlockBlock());
	public static final Block J_BLOCK = register(new JBlockBlock());
	public static final Block K_BLOCK = register(new KBlockBlock());
	public static final Block L_BLOCK = register(new LBlockBlock());
	public static final Block M_BLOCK = register(new MBlockBlock());
	public static final Block N_BLOCK = register(new NBlockBlock());
	public static final Block O_BLOCK = register(new OBlockBlock());
	public static final Block P_BLOCK = register(new PBlockBlock());
	public static final Block Q_BLOCK = register(new QBlockBlock());
	public static final Block R_BLOCK = register(new RBlockBlock());
	public static final Block S_BLOCK = register(new SBlockBlock());
	public static final Block T_BLOCK = register(new TBlockBlock());
	public static final Block U_BLOCK = register(new UBlockBlock());
	public static final Block V_BLOCK = register(new VBlockBlock());
	public static final Block W_BLOCK = register(new WBlockBlock());
	public static final Block X_BLOCK = register(new XBlockBlock());
	public static final Block Y_BLOCK = register(new YBlockBlock());
	public static final Block Z_BLOCK = register(new ZBlockBlock());
	public static final Block PERIOD_BLOCK = register(new PeriodBlockBlock());
	public static final Block EXCLAMATION_MARK_BLOCK = register(new ExclamationMarkBlockBlock());
	public static final Block QUESTION_MARK_BLOCK = register(new QuestionMarkBlockBlock());
	public static final Block LINE_BLOCK = register(new LineBlockBlock());
	public static final Block APOSTROPHE_BLOCK = register(new ApostropheBlockBlock());
	public static final Block SQUARE_BLOCK = register(new SquareBlockBlock());
	public static final Block CIRCLE_BLOCK = register(new CircleBlockBlock());
	public static final Block TRIANGLE_BLOCK = register(new TriangleBlockBlock());
	public static final Block DIAMOND_SYMBOL_BLOCK = register(new DiamondSymbolBlockBlock());
	public static final Block STAR_BLOCK = register(new StarBlockBlock());
	public static final Block DOT_BLOCK = register(new DotBlockBlock());
	public static final Block L_CA_BLOCK = register(new LCaBlockBlock());
	public static final Block L_CB_BLOCK = register(new LCbBlockBlock());
	public static final Block L_CC_BLOCK = register(new LCcBlockBlock());
	public static final Block L_CD_BLOCK = register(new LCdBlockBlock());
	public static final Block L_CE_BLOCK = register(new LCeBlockBlock());
	public static final Block L_CF_BLOCK = register(new LCfBlockBlock());
	public static final Block L_CG_BLOCK = register(new LCgBlockBlock());
	public static final Block L_CH_BLOCK = register(new LChBlockBlock());
	public static final Block L_CI_BLOCK = register(new LCiBlockBlock());
	public static final Block L_CJ_BLOCK = register(new LCjBlockBlock());
	public static final Block L_CK_BLOCK = register(new LCkBlockBlock());
	public static final Block L_CL_BLOCK = register(new LClBlockBlock());
	public static final Block L_CM_BLOCK = register(new LCmBlockBlock());
	public static final Block L_CN_BLOCK = register(new LCnBlockBlock());
	public static final Block L_CO_BLOCK = register(new LCoBlockBlock());
	public static final Block L_CP_BLOCK = register(new LCpBlockBlock());
	public static final Block L_CQ_BLOCK = register(new LCqBlockBlock());
	public static final Block L_CR_BLOCK = register(new LCrBlockBlock());
	public static final Block L_CS_BLOCK = register(new LCsBlockBlock());
	public static final Block L_CT_BLOCK = register(new LCtBlockBlock());
	public static final Block L_CU_BLOCK = register(new LCuBlockBlock());
	public static final Block L_CV_BLOCK = register(new LCvBlockBlock());
	public static final Block L_CW_BLOCK = register(new LCwBlockBlock());
	public static final Block L_CX_BLOCK = register(new LCxBlockBlock());
	public static final Block L_CY_BLOCK = register(new LCyBlockBlock());
	public static final Block L_CZ_BLOCK = register(new LCzBlockBlock());
	public static final Block MARBLE = register(new MarbleBlock());
	public static final Block CUT_MARBLE = register(new CutMarbleBlock());
	public static final Block POLISHED_MARBLE = register(new PolishedMarbleBlock());
	public static final Block MARBLE_BRICKS = register(new MarbleBricksBlock());
	public static final Block POLISHED_MARBLE_BRICKS = register(new PolishedMarbleBricksBlock());
	public static final Block MARBLE_SMALL_BRICKS = register(new MarbleSmallBricksBlock());
	public static final Block MARBLE_TILES = register(new MarbleTilesBlock());
	public static final Block MARBLE_PILLAR = register(new MarblePillarBlock());
	public static final Block FRET_PATTERNED_MARBLE = register(new FretPatternedMarbleBlock());
	public static final Block MARBLE_STAIRS = register(new MarbleStairsBlock());
	public static final Block CHISELLED_MARBLE = register(new ChiselledMarbleBlock());
	public static final Block MARBLE_SLAB = register(new MarbleSlabBlock());
	public static final Block MARBLE_WALL = register(new MarbleWallBlock());
	public static final Block POLISHED_MARBLE_STAIRS = register(new PolishedMarbleStairsBlock());
	public static final Block POLISHED_MARBLE_SLAB = register(new PolishedMarbleSlabBlock());
	public static final Block MARBLE_BRICK_STAIRS = register(new MarbleBrickStairsBlock());
	public static final Block MARBLE_BRICK_SLAB = register(new MarbleBrickSlabBlock());
	public static final Block MARBLE_BRICK_WALL = register(new MarbleBrickWallBlock());
	public static final Block POLISHED_MARBLE_BRICK_STAIRS = register(new PolishedMarbleBrickStairsBlock());
	public static final Block POLISHED_MARBLE_BRICK_SLAB = register(new PolishedMarbleBrickSlabBlock());
	public static final Block POLISHED_MARBLE_BRICK_WALL = register(new PolishedMarbleBrickWallBlock());
	public static final Block MARBLE_TILE_STAIRS = register(new MarbleTileStairsBlock());
	public static final Block MARBLE_TILE_SLAB = register(new MarbleTileSlabBlock());
	public static final Block MARBLE_TILE_WALL = register(new MarbleTileWallBlock());
	public static final Block SANDSTONE_BRICKS = register(new SandstoneBricksBlock());
	public static final Block CHISELLED_SANDSTONE_BRICKS = register(new ChiselledSandstoneBricksBlock());
	public static final Block SANDSTONE_TILES = register(new SandstoneTilesBlock());
	public static final Block CHISELLED_SANDSTONE_TILES = register(new ChiselledSandstoneTilesBlock());
	public static final Block SANDSTONE_PILLAR = register(new SandstonePillarBlock());
	public static final Block CHISELLED_SANDSTONE_PILLAR = register(new ChiselledSandstonePillarBlock());
	public static final Block SANDSTONE_BRICK_STAIRS = register(new SandstoneBrickStairsBlock());
	public static final Block SANDSTONE_BRICK_SLAB = register(new SandstoneBrickSlabBlock());
	public static final Block SANDSTONE_BRICK_WALL = register(new SandstoneBrickWallBlock());
	public static final Block CHISELLED_SANDSTONE_BRICK_STAIRS = register(new ChiselledSandstoneBrickStairsBlock());
	public static final Block CHISELLED_SANDSTONE_BRICK_SLAB = register(new ChiselledSandstoneBrickSlabBlock());
	public static final Block CHISELLED_SANDSTONE_BRICK_WALL = register(new ChiselledSandstoneBrickWallBlock());
	public static final Block SANDSTONE_TILE_STAIRS = register(new SandstoneTileStairsBlock());
	public static final Block SANDSTONE_TILE_SLAB = register(new SandstoneTileSlabBlock());
	public static final Block CHISELLED_SANDSTONE_TILE_STAIRS = register(new ChiselledSandstoneTileStairsBlock());
	public static final Block CHISELLED_SANDSTONE_TILE_SLAB = register(new ChiselledSandstoneTileSlabBlock());
	public static final Block CUT_SNOW = register(new CutSnowBlock());
	public static final Block SNOW_BRICKS = register(new SnowBricksBlock());
	public static final Block SMALL_SNOW_BRICKS = register(new SmallSnowBricksBlock());
	public static final Block SNOW_PILLAR = register(new SnowPillarBlock());
	public static final Block CUT_PACKED_ICE = register(new CutPackedIceBlock());
	public static final Block PACKED_ICE_BRICKS = register(new PackedIceBricksBlock());
	public static final Block PACKED_ICE_TILES = register(new PackedIceTilesBlock());
	public static final Block PACKED_ICE_PILLAR = register(new PackedIcePillarBlock());
	public static final Block CHISELLED_PACKED_ICE = register(new ChiselledPackedIceBlock());
	public static final Block CUT_ICE = register(new CutIceBlock());
	public static final Block ICE_BRICKS = register(new IceBricksBlock());
	public static final Block ICE_TILES = register(new IceTilesBlock());
	public static final Block CHISELLED_ICE = register(new ChiselledIceBlock());
	public static final Block ICE_PILLAR = register(new IcePillarBlock());

	private static Block register(Block block) {
		REGISTRY.add(block);
		return block;
	}

	@SubscribeEvent
	public static void registerBlocks(RegistryEvent.Register<Block> event) {
		event.getRegistry().registerAll(REGISTRY.toArray(new Block[0]));
	}

	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ClientSideHandler {
		@SubscribeEvent
		public static void clientSetup(FMLClientSetupEvent event) {
			OrangeSpoolBlock.registerRenderLayer();
			SlantedClayShinglesBlock.registerRenderLayer();
			SlantedShinglesSideBlock.registerRenderLayer();
			RedSlantedShinglesSideBlock.registerRenderLayer();
			RedSlantedClayShinglesBlock.registerRenderLayer();
			BlueSlantedClayShinglesBlock.registerRenderLayer();
			BlueSlantedShinglesSideBlock.registerRenderLayer();
			WovenBirchBasketBlock.registerRenderLayer();
			BirchBasketDirtBlock.registerRenderLayer();
			BirchBasketMossBlock.registerRenderLayer();
			BirchBasketMyceliumBlock.registerRenderLayer();
			BirchBasketPodzolBlock.registerRenderLayer();
			BirchBasketSandBlock.registerRenderLayer();
			WovenBasketBlock.registerRenderLayer();
			WovenBasketDirtBlock.registerRenderLayer();
			WovenBasketGrassBlock.registerRenderLayer();
			WovenBasketMyceliumBlock.registerRenderLayer();
			WovenBasketPodzolBlock.registerRenderLayer();
			WovenBasketSandBlock.registerRenderLayer();
			WovenSpruceBasketBlock.registerRenderLayer();
			SpruceBasketDirtBlock.registerRenderLayer();
			SpruceBasketMossBlock.registerRenderLayer();
			SpruceBasketPodzolBlock.registerRenderLayer();
			SpruceBasketMyceliumBlock.registerRenderLayer();
			SpruceBasketSandBlock.registerRenderLayer();
			WovenDarkOakBasketBlock.registerRenderLayer();
			DarkOakBasketDirtBlock.registerRenderLayer();
			DarkOakBasketMossBlock.registerRenderLayer();
			DarkOakBasketPodzolBlock.registerRenderLayer();
			DarkOakBasketMyceliumBlock.registerRenderLayer();
			DarkOakBasketSandBlock.registerRenderLayer();
			WovenJungleBasketBlock.registerRenderLayer();
			JungleBasketDirtBlock.registerRenderLayer();
			JungleBasketMossBlock.registerRenderLayer();
			JungleBasketPodzolBlock.registerRenderLayer();
			JungleBasketMyceliumBlock.registerRenderLayer();
			JungleBasketSandBlock.registerRenderLayer();
			WovenAcaciaBasketBlock.registerRenderLayer();
			AcaciaBasketDirtBlock.registerRenderLayer();
			AcaciaBasketMossBlock.registerRenderLayer();
			AcaciaBasketMyceliumBlock.registerRenderLayer();
			AcaciaBasketPodzolBlock.registerRenderLayer();
			AcaciaBasketSandBlock.registerRenderLayer();
			WovenCrimsonBasketBlock.registerRenderLayer();
			CrimsonBasketDirtBlock.registerRenderLayer();
			CrimsonBasketMossBlock.registerRenderLayer();
			CrimsonBasketPodzolBlock.registerRenderLayer();
			CrimsonBasketMyceliumBlock.registerRenderLayer();
			CrimsonBasketSandBlock.registerRenderLayer();
			WovenWarpedBasketBlock.registerRenderLayer();
			WarpedBasketDirtBlock.registerRenderLayer();
			WarpedBasketMossBlock.registerRenderLayer();
			WarpedBasketPodzolBlock.registerRenderLayer();
			WarpedBasketMyceliumBlock.registerRenderLayer();
			WarpedBasketSandBlock.registerRenderLayer();
			WovenMysticMapleBasketBlock.registerRenderLayer();
			BrassDoorBlock.registerRenderLayer();
			BrassTrapdoorBlock.registerRenderLayer();
			BrassChainsBlock.registerRenderLayer();
			BrassBarsMiddleBlock.registerRenderLayer();
			StringMeshBlock.registerRenderLayer();
			FramedStringMeshBlock.registerRenderLayer();
			RoseBlock.registerRenderLayer();
			RoseShrubBlock.registerRenderLayer();
			ScarletRoseBlock.registerRenderLayer();
			ScarletRoseBushBlock.registerRenderLayer();
			ScarletRoseShrubBlock.registerRenderLayer();
			BlushRoseBlock.registerRenderLayer();
			BlushRoseShrubBlock.registerRenderLayer();
			BlushRoseBushBlock.registerRenderLayer();
			PinkRoseBlock.registerRenderLayer();
			PinkRoseShrubBlock.registerRenderLayer();
			PinkRoseBushBlock.registerRenderLayer();
			ButtermilkRoseBlock.registerRenderLayer();
			ButtermilkRoseBushBlock.registerRenderLayer();
			ButtermilkRoseShrubBlock.registerRenderLayer();
			OliveRoseBlock.registerRenderLayer();
			OliveRoseShrubBlock.registerRenderLayer();
			OliveRoseBushBlock.registerRenderLayer();
			MysticMapleSaplingBlock.registerRenderLayer();
			BambooDreamcatcherBlock.registerRenderLayer();
			BambooLadderBlock.registerRenderLayer();
			BambooBasketBlock.registerRenderLayer();
			BambooWindChimesBlock.registerRenderLayer();
			DriedBambooDreamcatcherBlock.registerRenderLayer();
			DriedBambooLadderBlock.registerRenderLayer();
			DriedBambooBasketBlock.registerRenderLayer();
			DriedBambooWindChimesBlock.registerRenderLayer();
			DriedBambooBlock.registerRenderLayer();
			BrassBarsBlock.registerRenderLayer();
			BrassBarsTopBlock.registerRenderLayer();
			BrassBarsBottomBlock.registerRenderLayer();
			ArchiumVeinsBlock.registerRenderLayer();
			ArchiumTendrilsBlock.registerRenderLayer();
			EmptiedArchiumBlock.registerRenderLayer();
			CutIceBlock.registerRenderLayer();
			IceBricksBlock.registerRenderLayer();
			IceTilesBlock.registerRenderLayer();
			ChiselledIceBlock.registerRenderLayer();
			IcePillarBlock.registerRenderLayer();
		}

		@SubscribeEvent
		public static void blockColorLoad(ColorHandlerEvent.Block event) {
			BirchBasketMossBlock.blockColorLoad(event);
			WovenBasketGrassBlock.blockColorLoad(event);
		}
	}
}
